### ISSUE TITLE
I'm possibly about to break your config...

### ISSUE THREAD

**Issue by olimorris** [jwbaldwin/dotfiles#13]
Hey James

I [notice](https://github.com/jwbaldwin/dotfiles/blob/b21399f4786fb3c934a58b35b3f1840a3279ec53/.config/nvim/lua/core/plugins/configs.lua#L60) you use my [persisted.nvim](https://github.com/olimorris/persisted.nvim) plugin and the `branch_separator` config option. I'm actually planning on removing it in a refactor later today and just force `@@` as the separator across the plugin.

I wanted to check with you beforehand whether you'd come across a use case where `_` was the better choice of separator over `@@`?

**Comment by jwbaldwin** [comment]
Thanks for reaching out! I can't think of any specific case where `_` has been better than `@@` so I'm happy to adjust when I update!

**Comment by olimorris** [comment]
No worries. It might involve you having to update your session names and replacing `_` with `@@`
